// data.js — categories, school-policy config, and a research-backed library of
// toddler-safe lunch & snack items.
//
// Every item is NUT-FREE and SUNFLOWER-FREE (per the school handbook). Prep notes
// follow AAP/CDC choking guidance for under-4s (pieces ≤ ½", round/firm foods
// modified). `cold: true` = perishable, pack with an ice pack (USDA FSIS 2-hour rule).
// `allergens` flags common allergens; seed allergens (sesame/sunflower/pumpkin/chia/
// flax) are surfaced as a ⚠ because the school bans "nuts including sunflower seeds
// and certain seeds." See research/toddler-lunch-packing.md for sourcing.

const SCHOOL = {
  name: 'School',
  rules: [
    '🥜 Nut-free — including sunflower seeds & certain seeds',
    '🚫 No candy, chips, soda, cake, or gelatin/Jello',
    '🍱 Pack a lunch AND a snack every day',
    '❄️ Use an ice pack · 🏷️ label it · no glass containers',
  ],
};

// Allergens that fall under the school's "nuts + sunflower + certain seeds" ban and
// should be visually flagged for a second look.
const SEED_FLAG_ALLERGENS = ['sesame', 'sunflower', 'pumpkin', 'chia', 'flax'];

const CATEGORIES = [
  { key: 'protein', label: 'Protein', emoji: '🍗', color: '#f4a259' },
  { key: 'fruit',   label: 'Fruit',   emoji: '🍓', color: '#e76f8f' },
  { key: 'veg',     label: 'Veggie',  emoji: '🥦', color: '#6cc070' },
  { key: 'grain',   label: 'Grain',   emoji: '🍞', color: '#d6b25e' },
  { key: 'dairy',   label: 'Dairy',   emoji: '🧀', color: '#f2cd60' },
  { key: 'snack',   label: 'Snack',   emoji: '🍪', color: '#b08968' },
];

// A "balanced" lunchbox aims to cover these groups. Used by the builder's meter.
const BALANCE_GROUPS = ['protein', 'fruit', 'veg', 'grain'];

// cold: needs an ice pack. flag: optional extra caution shown on the item.
const SEED_ITEMS = [
  // ---- Proteins ----
  { id: 'egg-hard',     name: 'Hard-boiled egg',       category: 'protein', prep: 'Peeled, sliced into thin rounds or quartered; yolk fully cooked.', allergens: ['egg'], ingredients: ['eggs'], cold: true },
  { id: 'egg-scram',    name: 'Soft scrambled egg',    category: 'protein', prep: 'Cooked through but soft; broken into small bite-size pieces.', allergens: ['egg', 'dairy'], ingredients: ['eggs', 'butter'], cold: true },
  { id: 'chicken-shred',name: 'Shredded chicken',      category: 'protein', prep: 'Cooked & finely shredded, kept moist — no big chunks.', allergens: [], ingredients: ['chicken breast'], cold: true },
  { id: 'fish-flaked',  name: 'Flaked cooked fish',    category: 'protein', prep: 'Salmon/cod baked & flaked; ALL bones removed.', allergens: ['fish'], ingredients: ['salmon or cod fillet'], cold: true },
  { id: 'tuna',         name: 'Tuna (in water)',       category: 'protein', prep: 'Drained, lightly mashed; small spoonfuls.', allergens: ['fish'], ingredients: ['canned tuna in water'], cold: true },
  { id: 'turkey-rolls', name: 'Turkey roll-ups',       category: 'protein', prep: 'Thin low-sodium slices, rolled and cut into short strips.', allergens: [], ingredients: ['sliced turkey'], cold: true },
  { id: 'black-beans',  name: 'Black beans',           category: 'protein', prep: 'Soft-cooked, drained, lightly mashed.', allergens: [], ingredients: ['black beans'], cold: true },
  { id: 'chickpeas',    name: 'Chickpeas',             category: 'protein', prep: 'Drained, rinsed, skins off or slightly mashed (soft, not roasted-hard).', allergens: [], ingredients: ['chickpeas'], cold: true },
  { id: 'lentils',      name: 'Soft lentils',          category: 'protein', prep: 'Cooked until fully tender; can be lightly mashed.', allergens: [], ingredients: ['lentils'], cold: true },
  { id: 'tofu',         name: 'Soft tofu cubes',       category: 'protein', prep: 'Pressed, ½" cubes; lightly pan-warmed or soft.', allergens: ['soy'], ingredients: ['firm tofu'], cold: true },
  { id: 'edamame',      name: 'Edamame',               category: 'protein', prep: 'Cooked soft, fully SHELLED; halve beans (whole = choke risk).', allergens: ['soy'], ingredients: ['shelled edamame'], cold: true },
  { id: 'hummus',       name: 'Hummus (tahini-free)',  category: 'protein', prep: 'Use a SESAME/TAHINI-FREE hummus; serve as a dip with soft pita strips.', allergens: ['sesame', 'wheat'], ingredients: ['tahini-free hummus', 'pita bread'], cold: true, flag: 'Most hummus contains sesame (tahini) — buy a tahini-free one or skip.' },

  // ---- Fruits ----
  { id: 'blueberries',  name: 'Blueberries',           category: 'fruit', prep: 'Halved or lightly squished (whole = round choke risk).', allergens: [], ingredients: ['blueberries'], cold: true },
  { id: 'banana-coins', name: 'Banana coins',          category: 'fruit', prep: 'Peeled, sliced into thin coins; halve large ones.', allergens: [], ingredients: ['bananas'], cold: false },
  { id: 'strawberries', name: 'Strawberries',          category: 'fruit', prep: 'Hulled, sliced thin or quartered lengthwise.', allergens: [], ingredients: ['strawberries'], cold: true },
  { id: 'watermelon',   name: 'Watermelon',            category: 'fruit', prep: 'Seedless, ½" cubes (no melon balls — round).', allergens: [], ingredients: ['watermelon'], cold: true },
  { id: 'mandarin',     name: 'Mandarin segments',     category: 'fruit', prep: 'Segments halved; remove any seeds.', allergens: [], ingredients: ['mandarin oranges'], cold: true },
  { id: 'pear',         name: 'Soft pear',             category: 'fruit', prep: 'Ripe, peeled, cored, diced small.', allergens: [], ingredients: ['pears'], cold: true },
  { id: 'kiwi',         name: 'Kiwi',                  category: 'fruit', prep: 'Peeled, sliced into rounds then halved.', allergens: [], ingredients: ['kiwi'], cold: true },
  { id: 'pineapple',    name: 'Pineapple',             category: 'fruit', prep: 'Fresh or in juice (drained); ½" pieces.', allergens: [], ingredients: ['pineapple'], cold: true },
  { id: 'applesauce',   name: 'Applesauce pouch',      category: 'fruit', prep: 'Unsweetened. Shelf-stable until opened.', allergens: [], ingredients: ['unsweetened applesauce pouches'], cold: false },

  // ---- Veggies ----
  { id: 'carrot-soft',  name: 'Steamed carrots',       category: 'veg', prep: 'Steamed fork-soft, thin sticks (raw carrot = choke risk).', allergens: [], ingredients: ['carrots'], cold: true },
  { id: 'sweet-potato', name: 'Roasted sweet potato',  category: 'veg', prep: 'Baked very soft, peeled, ½" dice, cooled.', allergens: [], ingredients: ['sweet potato'], cold: true },
  { id: 'broccoli',     name: 'Steamed broccoli',      category: 'veg', prep: 'Steamed until very soft; small florets.', allergens: [], ingredients: ['broccoli'], cold: true },
  { id: 'green-beans',  name: 'Green beans',           category: 'veg', prep: 'Cooked tender, cut into ½" pieces.', allergens: [], ingredients: ['green beans'], cold: true },
  { id: 'peas',         name: 'Peas',                  category: 'veg', prep: 'Cooked soft; squish a few to reduce roundness.', allergens: [], ingredients: ['frozen peas'], cold: true },
  { id: 'cucumber',     name: 'Cucumber',              category: 'veg', prep: 'Peeled, quartered lengthwise, thin slices.', allergens: [], ingredients: ['cucumber'], cold: true },
  { id: 'avocado',      name: 'Avocado',               category: 'veg', prep: 'Ripe, ½" dice or thin slices (squeeze lemon to slow browning).', allergens: [], ingredients: ['avocado'], cold: true },
  { id: 'tomatoes',     name: 'Cherry tomatoes',       category: 'veg', prep: 'Quartered lengthwise — never whole/halved (round choke risk).', allergens: [], ingredients: ['cherry tomatoes'], cold: true },

  // ---- Grains ----
  { id: 'toast-strips', name: 'Toast strips',          category: 'grain', prep: 'Whole-grain, lightly toasted, finger-width strips.', allergens: ['wheat'], ingredients: ['whole-grain bread'], cold: false },
  { id: 'mini-pasta',   name: 'Soft pasta',            category: 'grain', prep: 'Whole-wheat, cooked soft (past al dente); small shapes.', allergens: ['wheat'], ingredients: ['mini whole-wheat pasta'], cold: true },
  { id: 'brown-rice',   name: 'Brown rice',            category: 'grain', prep: 'Cooked soft; small spoonfuls.', allergens: [], ingredients: ['brown rice'], cold: true },
  { id: 'oatmeal',      name: 'Oatmeal',               category: 'grain', prep: 'Plain rolled oats cooked to soft porridge; room temp.', allergens: [], ingredients: ['rolled oats'], cold: false },
  { id: 'crackers',     name: 'Whole-grain crackers',  category: 'grain', prep: 'Soft-ish; offer with water. Check label is nut/seed-free.', allergens: ['wheat'], ingredients: ['whole-grain crackers'], cold: false },
  { id: 'rice-cakes',   name: 'Brown rice cakes',      category: 'grain', prep: 'Plain; break into pieces, offer with water.', allergens: [], ingredients: ['brown rice cakes'], cold: false },
  { id: 'pita',         name: 'Pita / tortilla strips',category: 'grain', prep: 'Whole-wheat, soft, cut into small strips or triangles.', allergens: ['wheat'], ingredients: ['whole-wheat pita or tortillas'], cold: false },

  // ---- Dairy ----
  { id: 'yogurt',       name: 'Whole-milk yogurt',     category: 'dairy', prep: 'Plain / no added sugar; small cup or pouch.', allergens: ['dairy'], ingredients: ['whole-milk yogurt'], cold: true },
  { id: 'greek-yogurt', name: 'Greek yogurt',          category: 'dairy', prep: 'Plain full-fat; higher protein. No added sugar.', allergens: ['dairy'], ingredients: ['plain Greek yogurt'], cold: true },
  { id: 'cheese-shred', name: 'Shredded cheese',       category: 'dairy', prep: 'Cheddar/mozzarella shredded or thin pieces (not a hard stick/cube).', allergens: ['dairy'], ingredients: ['mild cheese'], cold: true },
  { id: 'babybel',      name: 'Babybel pieces',        category: 'dairy', prep: 'Wrapper off, cut into small pea-size pieces.', allergens: ['dairy'], ingredients: ['Babybel mini cheeses'], cold: true },
  { id: 'cottage',      name: 'Cottage cheese',        category: 'dairy', prep: 'Small-curd, small spoonfuls.', allergens: ['dairy'], ingredients: ['cottage cheese'], cold: true },
  { id: 'cream-cheese', name: 'Cream cheese',          category: 'dairy', prep: 'Spread THIN on toast/crackers — never a thick glob.', allergens: ['dairy', 'wheat'], ingredients: ['cream cheese', 'whole-grain bread'], cold: true },

  // ---- Snacks ----
  { id: 'mini-muffin',  name: 'Whole-grain mini muffin',category: 'snack', prep: 'Homemade low-sugar (banana-oat/zucchini); quartered. Nut/seed-free batter.', allergens: ['wheat', 'egg'], ingredients: ['flour', 'oats', 'bananas', 'egg'], cold: false },
  { id: 'fd-fruit',     name: 'Freeze-dried fruit',    category: 'snack', prep: 'No added sugar; dissolves easily. Offer with water.', allergens: [], ingredients: ['freeze-dried fruit'], cold: false },
  { id: 'fruit-cup',    name: 'Fruit cup (in juice)',  category: 'snack', prep: 'Packed in 100% juice/water (no syrup); drain, cut any large pieces.', allergens: [], ingredients: ['fruit cups in juice'], cold: false },
  { id: 'o-cereal',     name: 'Whole-grain O cereal',  category: 'snack', prep: 'Plain low-sugar; dry finger food.', allergens: ['wheat'], ingredients: ['plain O-shaped cereal'], cold: false },
  { id: 'veg-pouch',    name: 'Veggie/fruit pouch',    category: 'snack', prep: '100% fruit & veg, no added sugar. Squeeze onto a spoon.', allergens: [], ingredients: ['fruit & veg pouches'], cold: false },

  // ---- Make-ahead recipes (recipe:true → tap to see steps; freezer-friendly) ----
  { id: 'r-egg-muffins', name: 'Egg & veggie muffins', category: 'protein', recipe: true, prep: 'Cut into small soft pieces. Iron + protein; hides veggies.', allergens: ['egg', 'dairy'], ingredients: ['eggs', 'shredded cheese', 'spinach', 'bell pepper'], cold: true, yield: '12 mini muffins', freezer: 'Freeze up to 3 months; thaw overnight in the fridge.', steps: [
      'Heat oven to 350°F. Grease a 12-cup mini muffin tin.',
      'Whisk 6 eggs with a splash of milk.',
      'Finely chop a handful of spinach + bell pepper; stir in with ¼ cup shredded cheese.',
      'Fill cups ¾ full. Bake 15–18 min until set.',
      'Cool fully, then refrigerate 3 days or freeze.' ] },
  { id: 'r-meatballs', name: 'Baked chicken meatballs', category: 'protein', recipe: true, prep: 'Quarter each meatball before serving (round = choke risk).', allergens: ['egg', 'wheat'], ingredients: ['ground chicken', 'breadcrumbs', 'egg', 'grated carrot'], cold: true, yield: '~20 small', freezer: 'Freeze cooked & cooled up to 3 months.', steps: [
      'Heat oven to 400°F. Line a tray with parchment.',
      'Mix 1 lb ground chicken, ½ cup breadcrumbs, 1 egg, ½ cup finely grated carrot, pinch of salt.',
      'Roll into small balls; bake 18–20 min until cooked through (165°F).',
      'Cool, then refrigerate 3 days or freeze. Quarter before packing.' ] },
  { id: 'r-quesadilla', name: 'Bean & cheese quesadilla', category: 'grain', recipe: true, prep: 'Cut into small strips or triangles.', allergens: ['wheat', 'dairy'], ingredients: ['whole-wheat tortillas', 'shredded cheese', 'refried/mashed beans'], cold: true, yield: '4 quesadillas', freezer: 'Freeze 3 months; reheat from frozen.', steps: [
      'Spread mashed beans on a tortilla, sprinkle cheese, top with another tortilla.',
      'Cook in a dry pan ~2 min per side until cheese melts.',
      'Cool, cut into small strips. Refrigerate 2–3 days or freeze.' ] },
  { id: 'r-oat-bites', name: 'No-bake oat bites', category: 'snack', recipe: true, prep: 'Soft; break into pieces for younger eaters.', allergens: [], ingredients: ['rolled oats', 'mashed banana', 'honey'], cold: false, flag: 'Honey is fine for ages 1+ — never for a baby under 12 months.', yield: '~15 bites', freezer: 'Freeze 3 months on a tray, then bag.', steps: [
      'Mash 1 ripe banana; mix with 1½ cups rolled oats and a drizzle of honey.',
      'Roll into small balls.',
      'Chill 30 min to firm up. Refrigerate 1 week or freeze.' ] },
  { id: 'r-pinwheels', name: 'Cream-cheese pinwheels', category: 'grain', recipe: true, prep: 'Slice into thin rounds.', allergens: ['wheat', 'dairy'], ingredients: ['whole-wheat tortillas', 'cream cheese'], cold: true, yield: '2 wraps', freezer: 'Flash-freeze; keeps 2–3 months. Avoid watery fillings.', steps: [
      'Spread a thin layer of cream cheese over a tortilla (no watery fillings — they go soggy).',
      'Roll tightly, then slice into thin pinwheels.',
      'Refrigerate same-day, or flash-freeze on a tray then bag.' ] },

  { id: 'r-sweetpotato-bites', name: 'Sweet potato & chickpea bites', category: 'protein', recipe: true, prep: 'Soft baked patties; serve in small pieces.', allergens: ['egg', 'wheat'], ingredients: ['sweet potato', 'chickpeas', 'breadcrumbs', 'egg'], cold: true, yield: '~16 bites', freezer: 'Freeze cooked & cooled up to 3 months.', nutrients: ['iron', 'protein', 'fiber', 'vitc'], steps: [
      'Bake or steam 1 sweet potato until very soft; mash with 1 cup drained chickpeas.',
      'Mix in ⅓ cup breadcrumbs and 1 egg; season lightly.',
      'Scoop small patties onto a lined tray; bake 400°F for ~20 min, flipping once.',
      'Cool fully. Refrigerate 3 days or freeze.' ] },
  { id: 'r-zucchini-muffins', name: 'Zucchini-carrot mini muffins', category: 'snack', recipe: true, prep: 'Quarter each mini muffin.', allergens: ['wheat', 'egg'], ingredients: ['flour', 'grated zucchini', 'grated carrot', 'egg', 'oil'], cold: false, yield: '12 mini muffins', freezer: 'Freeze up to 3 months; thaw at room temp.', nutrients: ['fiber'], steps: [
      'Heat oven to 350°F; grease a mini muffin tin.',
      'Mix 1 cup flour, ½ tsp baking powder, 1 egg, ¼ cup oil, and ½ cup each grated zucchini + carrot (squeeze zucchini dry first).',
      'Fill cups ¾ full; bake 15–18 min.',
      'Cool fully. Keeps 3 days, or freeze.' ] },
  { id: 'r-pancake-bites', name: 'Banana-oat pancake bites', category: 'grain', recipe: true, prep: 'Mini pancakes; cut into pieces.', allergens: ['wheat', 'egg', 'dairy'], ingredients: ['flour', 'oats', 'mashed banana', 'milk', 'egg'], cold: false, yield: '~20 mini', freezer: 'Freeze in a bag up to 2 months; toast to reheat.', nutrients: ['fiber'], steps: [
      'Blend 1 banana, 1 cup flour, ½ cup oats, 1 egg, ¾ cup milk, 1 tsp baking powder.',
      'Cook small silver-dollar pancakes on a greased pan.',
      'Cool. Refrigerate 3 days or freeze flat in a bag.' ] },
  { id: 'r-veggie-nuggets', name: 'Lentil & veggie nuggets', category: 'protein', recipe: true, prep: 'Soft nuggets; cut in half to serve.', allergens: ['wheat', 'egg', 'dairy'], ingredients: ['cooked lentils', 'grated carrot', 'breadcrumbs', 'shredded cheese', 'egg'], cold: true, yield: '~18 nuggets', freezer: 'Freeze cooked up to 3 months.', nutrients: ['iron', 'protein', 'fiber'], steps: [
      'Mash 1 cup soft-cooked lentils; mix with ½ cup grated carrot, ½ cup breadcrumbs, ¼ cup cheese, 1 egg.',
      'Shape into small nuggets on a lined tray.',
      'Bake 400°F ~18–20 min until firm. Cool, then refrigerate 3 days or freeze.' ] },
  { id: 'r-broccoli-bites', name: 'Cheesy broccoli & rice bites', category: 'grain', recipe: true, prep: 'Soft baked bites; small pieces.', allergens: ['dairy', 'egg'], ingredients: ['cooked rice', 'finely chopped broccoli', 'shredded cheese', 'egg'], cold: true, yield: '~14 bites', freezer: 'Freeze up to 2 months.', nutrients: ['calcium', 'fiber', 'protein'], steps: [
      'Steam broccoli very soft and chop finely.',
      'Mix 1½ cups cooked rice, 1 cup broccoli, ¾ cup cheese, 2 eggs.',
      'Press into a greased mini muffin tin; bake 375°F ~20 min.',
      'Cool fully. Refrigerate 3 days or freeze.' ] },
  { id: 'r-burritos', name: 'Mini bean & cheese burritos', category: 'grain', recipe: true, prep: 'Cut into short, small pieces.', allergens: ['wheat', 'dairy'], ingredients: ['small tortillas', 'mashed beans', 'shredded cheese'], cold: true, yield: '6 mini burritos', freezer: 'Wrap individually; freeze up to 3 months.', nutrients: ['protein', 'fiber', 'calcium'], steps: [
      'Spread mashed beans on a small tortilla, add a little cheese.',
      'Roll up and tuck the ends; warm in a pan to seal.',
      'Cool, wrap each one. Refrigerate 3 days or freeze.' ] },
  { id: 'r-oat-squares', name: 'Apple-cinnamon baked oat squares', category: 'snack', recipe: true, prep: 'Cut into small soft squares.', allergens: ['egg', 'dairy'], ingredients: ['rolled oats', 'grated apple', 'milk', 'egg', 'cinnamon'], cold: false, yield: '9 squares', freezer: 'Freeze up to 3 months; thaw or warm.', nutrients: ['fiber'], steps: [
      'Mix 2 cups oats, 1 grated apple, 1¼ cups milk, 1 egg, 1 tsp cinnamon, 1 tsp baking powder.',
      'Spread in a greased 8x8 pan; bake 375°F ~25 min.',
      'Cool, cut into squares. Refrigerate 4 days or freeze.' ] },
  { id: 'r-french-toast', name: 'French toast sticks', category: 'grain', recipe: true, prep: 'Cut bread into finger-width sticks.', allergens: ['wheat', 'egg', 'dairy'], ingredients: ['whole-grain bread', 'egg', 'milk', 'cinnamon'], cold: false, yield: '~12 sticks', freezer: 'Freeze flat; toast straight from frozen.', nutrients: ['protein', 'fiber'], steps: [
      'Whisk 2 eggs, ¼ cup milk, a little cinnamon.',
      'Cut bread into sticks; dip and cook on a greased pan until golden.',
      'Cool. Refrigerate 2 days or freeze flat in a bag.' ] },
  { id: 'r-carrot-tots', name: 'Baked carrot & potato tots', category: 'veg', recipe: true, prep: 'Soft tots; halve to serve.', allergens: ['egg', 'dairy', 'wheat'], ingredients: ['grated potato', 'grated carrot', 'shredded cheese', 'egg', 'breadcrumbs'], cold: true, yield: '~20 tots', freezer: 'Freeze cooked up to 2 months.', nutrients: ['fiber', 'vitc'], steps: [
      'Squeeze 1 cup grated potato + ½ cup grated carrot dry.',
      'Mix with ¼ cup cheese, 1 egg, ¼ cup breadcrumbs.',
      'Shape small tots; bake 425°F ~20 min, flipping once.',
      'Cool. Refrigerate 3 days or freeze.' ] },
  { id: 'r-cottage-pancakes', name: 'Cottage cheese banana pancakes', category: 'protein', recipe: true, prep: 'Soft mini pancakes; cut up.', allergens: ['wheat', 'egg', 'dairy'], ingredients: ['cottage cheese', 'mashed banana', 'egg', 'flour'], cold: false, yield: '~16 mini', freezer: 'Freeze in a bag up to 2 months.', nutrients: ['calcium', 'protein'], steps: [
      'Blend ½ cup cottage cheese, 1 banana, 1 egg, ½ cup flour.',
      'Cook small pancakes on a greased pan.',
      'Cool. Refrigerate 2 days or freeze flat.' ] },

  // ===== Asian recipes (nut-free + sesame-free; see research/asian-toddler-lunch-recipes.md) =====
  // ---- Chinese ----
  { id: 'a-congee', name: 'Congee / jook (rice porridge)', category: 'grain', recipe: true, prep: 'Silky-soft — one of the safest toddler textures. Serve warm from a thermos.', allergens: [], ingredients: ['white rice', 'water or low-sodium broth', 'fresh ginger'], cold: true, yield: '4 servings', freezer: 'Freeze cooked up to 1 month; reheat with a splash of water.', nutrients: ['fiber'], flag: 'Pack hot in a thermos. Never use mochi/sticky rice — choking hazard; plain rice only.', steps: [
      'Rinse ¾ cup rice; simmer with 7 cups water/broth + a few ginger slices.',
      'Cook 20–30 min, stirring, until broken-down and creamy. Remove ginger.',
      'Stir in soft add-ins (mashed egg, shredded chicken, silken tofu) if you like.',
      'Cool quickly if storing; reheat piping hot and pack in a warmed thermos.' ] },
  { id: 'a-steamed-egg', name: 'Steamed egg custard (蒸蛋)', category: 'protein', recipe: true, prep: 'Silky, spoon-soft — ideal for toddlers.', allergens: ['egg'], ingredients: ['eggs', 'water or low-sodium broth'], cold: true, yield: '3–4 servings', freezer: 'Best fresh (texture weeps if frozen). Make day-of.', nutrients: ['protein', 'iron'], flag: 'Omit the sesame oil to keep it school-compliant — a drop of neutral oil + scallion is plenty.', steps: [
      'Beat 3 eggs; add an equal volume of water/broth and a little salt.',
      'Strain into a shallow heatproof dish; cover with foil.',
      'Steam 3 min on high, then off-heat (lid shut) 14 min — don\'t peek.',
      'Top with minced scallion. Serve warm or room temp.' ] },
  { id: 'a-tomato-egg', name: 'Tomato & egg (番茄炒蛋)', category: 'protein', recipe: true, prep: 'Cut tomato small and cook fully soft; eggs in small soft pieces. Serve over soft rice.', allergens: ['egg'], ingredients: ['ripe tomatoes', 'eggs', 'neutral oil', 'a little sugar'], cold: true, yield: '3 servings', freezer: 'Best fresh; refrigerate up to 2 days.', nutrients: ['protein', 'vitc', 'iron'], flag: 'Traditionally has no sesame — naturally school-safe.', steps: [
      'Cut 4 small tomatoes into small wedges; beat 4 eggs with a pinch of salt.',
      'Scramble eggs soft in oil; set aside.',
      'Stir-fry tomatoes with a little sugar + splash of water until fully soft.',
      'Fold eggs back in; serve over soft rice.' ] },
  { id: 'a-scallion-pancake', name: 'Easy scallion pancakes', category: 'grain', recipe: true, prep: 'Soft shortcut version (dumpling wrappers). Cut into small strips; cook on medium so they stay pliable.', allergens: ['wheat'], ingredients: ['round dumpling wrappers', 'scallions', 'neutral oil', 'salt'], cold: false, yield: '4–6 pancakes', freezer: 'Freeze uncooked between parchment; cook from frozen.', nutrients: ['fiber'], flag: 'This shortcut version uses no sesame oil — check the wrapper label is sesame-free.', steps: [
      'Brush a wrapper with oil; sprinkle salt + chopped scallion; stack another on top. Repeat 4–6 layers.',
      'Roll the stack into a thin pancake.',
      'Cook ~2–3 min per side on medium until golden.',
      'Cut into small strips or squares; cool before packing.' ] },

  // ---- Japanese ----
  { id: 'a-onigiri', name: 'Onigiri (rice balls)', category: 'grain', recipe: true, prep: 'Shape small for little hands; break into pieces for under-2s.', allergens: [], ingredients: ['Japanese short-grain rice', 'salt', 'unseasoned nori (optional)'], cold: true, yield: '6 small balls', freezer: 'Freeze plain cooked rice, not shaped balls; reshape fresh.', nutrients: ['fiber'], flag: 'Use UNSEASONED nori torn into small strips (it gets gummy). NEVER mochi/glutinous rice — serious choking hazard.', steps: [
      'Cook short-grain rice; cool until just warm.',
      'Wet hands, salt lightly, press ~½ cup rice into a ball or triangle.',
      'Add a tiny soft filling (flaked salmon, tuna-mayo) if you like.',
      'Wrap a small nori strip around the base, or skip for toddlers. Eat within ~6 hrs with an ice pack.' ] },
  { id: 'a-tamagoyaki', name: 'Tamagoyaki (rolled egg)', category: 'protein', recipe: true, prep: 'Cut into finger-width pieces; fully cooked, soft and cohesive.', allergens: ['egg', 'soy'], ingredients: ['eggs', 'a little sugar', 'light soy sauce', 'neutral oil'], cold: true, yield: '6 pieces', freezer: 'Freeze up to 1 month; thaw in the fridge.', nutrients: ['protein'], flag: 'Naturally sesame-free.', steps: [
      'Mix 3 eggs with ½ Tbsp sugar, a pinch of salt, 1 tsp soy sauce, 1 Tbsp water.',
      'Grease a pan; pour a thin layer, let it set, roll to one side.',
      'Grease, add next layer, roll again — repeat 3–4 times into a log.',
      'Cool, slice into 6; cut small for toddlers.' ] },
  { id: 'a-kabocha', name: 'Simmered kabocha squash', category: 'veg', recipe: true, prep: 'Simmered velvety-soft; peel skin off for under-2s, cut into ~1 cm cubes.', allergens: ['soy'], ingredients: ['kabocha squash', 'water', 'a little sugar', 'light soy sauce'], cold: true, yield: '4 servings', freezer: 'Freezes 2–3 weeks (softens slightly).', nutrients: ['fiber', 'vitc'], flag: 'Naturally sesame-free. A classic bento veg.', steps: [
      'Cut kabocha into 2-inch pieces.',
      'Simmer skin-side down in water + a little sugar, covered, 20–30 min until a skewer slides in.',
      'Add a splash of soy sauce near the end; rest 30 min to soak up flavor.',
      'Peel + cube small for toddlers. Good warm or cold.' ] },
  { id: 'a-mushipan', name: 'Mushi-pan (steamed cake)', category: 'snack', recipe: true, prep: 'Soft, spongy; serve room temp in quarters.', allergens: ['wheat', 'egg', 'dairy'], ingredients: ['flour', 'baking powder', 'egg', 'milk', 'a little sugar', 'oil'], cold: false, yield: '4 small cakes', freezer: 'Freeze up to 1 month; thaw at room temp.', nutrients: [], flag: 'Naturally sesame-free. Fold in mashed sweet potato for extra nutrition.', steps: [
      'Whisk ½ cup flour + 1 tsp baking powder.',
      'Mix 1 egg, 2 Tbsp milk, 2 Tbsp sugar, 1 Tbsp oil; combine with the dry.',
      'Spoon into cupcake liners in ramekins.',
      'Steam, covered (towel under lid), ~8 min until a skewer is clean. Cool.' ] },

  // ---- Korean ----
  { id: 'a-gyeranmari', name: 'Gyeran-mari (Korean rolled egg)', category: 'protein', recipe: true, prep: 'Slice into ¾-inch rounds; soft, low choking risk.', allergens: ['egg'], ingredients: ['eggs', 'finely minced carrot', 'finely minced scallion', 'neutral oil', 'salt'], cold: true, yield: '4 servings', freezer: 'Best within 2–3 days refrigerated.', nutrients: ['protein'], flag: 'A popular Korean lunchbox dish that is naturally sesame-free.', steps: [
      'Beat 3 eggs with finely minced carrot + scallion and a little salt.',
      'Pour a thin layer into a greased pan over medium-low.',
      'As it sets, roll it up; add more egg and keep rolling into a log.',
      'Cool, then slice into rounds.' ] },
  { id: 'a-mandu', name: 'Veggie & tofu mandu (steamed)', category: 'protein', recipe: true, prep: 'Steam (softest); cut each dumpling in half. Mince filling fine.', allergens: ['wheat', 'soy', 'egg'], ingredients: ['round dumpling wrappers', 'firm tofu (squeezed)', 'ground chicken or pork', 'blanched chopped mung sprouts', 'onion', 'egg'], cold: true, yield: '~30 dumplings', freezer: 'Freeze raw on a tray then bag; steam from frozen.', nutrients: ['protein', 'fiber'], flag: 'This filling uses no sesame oil — check the wrapper label is sesame-free.', steps: [
      'Squeeze tofu dry; blanch + finely chop sprouts.',
      'Mix tofu, meat, sprouts, minced onion, 1 egg, salt + pepper.',
      'Spoon filling onto wrappers; wet edges and seal.',
      'Steam ~10 min until cooked through. Cool, halve before serving.' ] },

  // ---- Vietnamese ----
  { id: 'a-chaoga', name: 'Cháo gà (chicken congee)', category: 'grain', recipe: true, prep: 'Porridge — very safe texture. Shred chicken into fine strands. Skip fried-shallot topping.', allergens: [], ingredients: ['jasmine rice', 'chicken (thighs or breast)', 'ginger', 'shallot', 'low-sodium broth'], cold: true, yield: '4–6 servings', freezer: 'Freeze chicken + broth separately up to 3 months.', nutrients: ['protein', 'fiber'], flag: 'Pack hot in a thermos. Naturally sesame-free; keep sodium low for a toddler.', steps: [
      'Simmer chicken with ginger + shallot until cooked; shred finely, keep the broth.',
      'Simmer 1 cup rinsed rice in 6 cups broth 30–40 min until porridgey.',
      'Season lightly; stir in shredded chicken.',
      'Top with a little scallion. Pack hot in a warmed thermos.' ] },
  { id: 'a-xiumai', name: 'Xíu mại (pork meatballs in tomato)', category: 'protein', recipe: true, prep: 'Make small; cut each meatball in half (round = choke risk). Tomato sauce keeps them moist.', allergens: ['fish'], ingredients: ['ground pork', 'finely diced jicama', 'scallion whites', 'tomatoes', 'tomato paste', 'a little fish sauce'], cold: true, yield: '~16 meatballs', freezer: 'Freeze raw meatballs on a tray then bag.', nutrients: ['protein', 'vitc'], flag: 'Naturally sesame-free. Use just a few drops of fish sauce for a toddler (or swap a little soy).', steps: [
      'Mix pork, finely diced jicama, minced scallion whites, a little fish sauce + cornstarch.',
      'Roll small balls.',
      'Simmer in a simple tomato sauce (tomato + paste + a little sugar + water), covered, ~10 min.',
      'Serve over soft rice; halve meatballs for toddlers.' ] },

  // ---- South Asian ----
  { id: 'a-khichdi', name: 'Moong dal khichdi', category: 'grain', recipe: true, prep: 'Mash to a soft porridge while hot. Remove any whole spices before serving.', allergens: ['dairy'], ingredients: ['rice', 'moong dal (split yellow lentils)', 'soft diced vegetables', 'a little ghee', 'turmeric'], cold: true, yield: '3–4 servings', freezer: 'Best fresh; refrigerate up to 1 day. Pack hot in a thermos.', nutrients: ['iron', 'protein', 'fiber'], flag: 'Naturally sesame-free. Skip green chilli; pack hot in a thermos (serve warm, not lukewarm).', steps: [
      'Rinse + soak ¼ cup each rice and moong dal ~30 min.',
      'Pressure-cook with soft-diced veg, a pinch of turmeric and ~1¼ cups water until very soft.',
      'Mash together while hot; stir in a little ghee.',
      'Loosen with hot water to a porridge; cool to safe temp before serving.' ] },
  { id: 'a-besan-chilla', name: 'Besan chilla (chickpea pancake)', category: 'grain', recipe: true, prep: 'Cook soft (squish-test); cut into small strips.', allergens: [], ingredients: ['besan (chickpea flour)', 'water', 'finely grated veg (carrot/zucchini)', 'ajwain', 'turmeric'], cold: false, yield: '4 chillas', freezer: 'Best fresh; batter keeps 1 day.', nutrients: ['protein', 'fiber'], flag: 'Naturally nut- and sesame-free; a great veggie-hiding protein pancake.', steps: [
      'Whisk ¾ cup besan with ¾ cup water, a pinch of turmeric + ajwain; rest 10 min.',
      'Stir in finely grated veg + chopped coriander.',
      'Pour medium-thick rounds on a lightly oiled pan; cook ~2½ min per side until set.',
      'Cool; cut into strips.' ] },
  { id: 'a-curd-rice', name: 'Curd rice (thayir sadam)', category: 'dairy', recipe: true, prep: 'Rice soft/mushy; serve cool — great for hot days. Skip green chilli.', allergens: ['dairy'], ingredients: ['cooked soft rice', 'plain whole-milk yogurt', 'a little milk', 'curry leaves', 'mustard seeds', 'neutral oil'], cold: true, yield: '3 servings', freezer: 'Make rice ahead; mix with fresh yogurt day-of.', nutrients: ['calcium', 'protein'], flag: 'Use NEUTRAL oil for the tadka, NOT sesame/gingelly oil — keeps it school-compliant. Omit any cashew garnish.', steps: [
      'Cook rice very soft; cool and mash lightly.',
      'Stir in yogurt + a splash of milk to a creamy consistency.',
      'Make a quick tempering in neutral oil: pop mustard seeds, add curry leaves + a pinch of hing; stir in.',
      'Serve cool or at room temp.' ] },
  { id: 'a-idli', name: 'Steamed idli', category: 'grain', recipe: true, prep: 'Naturally soft and toddler-friendly; serve mini idlis or quartered.', allergens: [], ingredients: ['idli rice', 'urad dal', 'fenugreek seeds'], cold: false, yield: 'batter makes many', freezer: 'Batter keeps 5 days refrigerated; steam fresh daily.', nutrients: ['fiber', 'protein'], flag: 'Skip idli podi (it contains SESAME) and restaurant coconut chutney (often has cashew). Serve with plain curd or mild sambar.', steps: [
      'Soak rice and urad dal (with a little fenugreek) ~6–8 hrs; grind to a thick batter.',
      'Ferment overnight until bubbly.',
      'Pour into greased idli moulds; steam ~10–12 min until a toothpick is clean.',
      'Cool 2 min; serve with plain curd (no sesame podi).' ] },
  // --- expanded recipe library (mega-wide research batch, 2026-06-03) ---
  {"id": "l-arepas", "name": "Cheese-Stuffed Arepas", "category": "grain", "recipe": true, "prep": "Griddle corn cakes with melty cheese inside; serve fully cooled, cut into ~1/2\" strips, no large round disc.", "allergens": ["dairy"], "ingredients": ["masarepa (pre-cooked white corn flour)", "shredded mozzarella or mild white cheese", "warm water", "salt", "neutral oil"], "cold": true, "yield": "6 small arepas", "freezer": "Freeze cooked arepas up to 1 month; thaw and re-griddle.", "nutrients": ["calcium", "fiber", "protein"], "flag": "Cut into finger strips before serving; whole round disc is a choking shape for under-4.", "steps": ["Mix 1 cup masarepa with a pinch of salt, stir in ~1 cup warm water until a soft non-sticky dough forms; rest 5 min.", "Divide into 6 balls, flatten to ~1/2\" patties, tuck shredded cheese into the center, seal edges.", "Griddle on medium-low in a lightly oiled pan ~5-6 min per side until golden and cheese melts.", "Cool completely, then cut each into ~1/2\" strips before packing."]},
  {"id": "l-black-bean-cheese-cakes", "name": "Black Bean & Cheese Soft Cakes", "category": "protein", "recipe": true, "prep": "Pan-baked mashed-bean patties with cheese; serve cooled and broken into ~1/2\" pieces.", "allergens": ["dairy", "egg", "wheat"], "ingredients": ["canned black beans (no-salt-added, rinsed)", "shredded mild cheddar", "egg", "plain breadcrumbs", "neutral oil"], "cold": true, "yield": "8 small cakes", "freezer": "Freeze cooked cakes up to 1 month; reheat from frozen.", "nutrients": ["protein", "iron", "fiber"], "flag": "Rinse canned beans well to cut sodium; break cakes into bite pieces.", "steps": ["Mash 1.5 cups rinsed black beans until mostly smooth.", "Stir in 1/2 cup cheese, 1 beaten egg, and 1/3-1/2 cup breadcrumbs until it holds together.", "Form 8 small patties ~1/2\" thick and pan-bake in a lightly oiled skillet on medium-low ~4 min per side.", "Cool fully, then break each cake into ~1/2\" pieces before packing."]},
  {"id": "l-maduros", "name": "Soft Sweet Plantain (Maduros)", "category": "fruit", "recipe": true, "prep": "Pan-cook very ripe plantain until soft; quarter lengthwise, cook fully soft, no firm rounds.", "allergens": ["dairy"], "ingredients": ["very ripe (black-spotted) plantains", "unsalted butter or neutral oil"], "cold": true, "yield": "3-4 servings", "freezer": "Freeze cooked maduros up to 1 month; reheat gently.", "nutrients": ["vitc", "fiber"], "flag": "Use oil instead of butter to keep dairy-free; quarter lengthwise so there are no round coins.", "steps": ["Peel ripe plantains and cut each into quarters lengthwise (long soft strips, not rounds).", "Melt a little butter or oil in a pan over medium-low heat.", "Cook strips ~3-4 min per side until deeply golden and fork-soft throughout.", "Cool, then cut soft strips into ~1/2\" pieces before packing."]},
  {"id": "l-pao-de-queijo", "name": "Pao de Queijo (Tapioca Cheese Bread)", "category": "grain", "recipe": true, "prep": "Bake naturally gluten-free tapioca-cheese rolls; serve cooled, cut small rolls in half.", "allergens": ["dairy", "egg"], "ingredients": ["tapioca (cassava/sour) flour", "whole milk", "egg", "grated parmesan", "neutral oil", "salt"], "cold": true, "yield": "12 small rolls", "freezer": "Freeze unbaked dough balls; bake from frozen adding a few minutes.", "nutrients": ["calcium", "protein"], "flag": "Naturally gluten-free (no wheat). Cut small rolls in half so toddler isn't biting a whole springy ball.", "steps": ["Heat 1/2 cup milk with 3 tbsp oil and a pinch of salt to a gentle simmer, stir into 1 cup tapioca flour to a sticky paste; cool 10 min.", "Beat in 1 egg and 1/2 cup grated parmesan until a smooth stretchy dough forms.", "Roll into 12 small balls, place on a lined tray, bake at 375F ~20-25 min until puffed and lightly golden.", "Cool fully, then cut each roll in half before packing."]},
  {"id": "l-arroz-feijao", "name": "Brazilian Rice & Black Beans", "category": "grain", "recipe": true, "prep": "Soft white rice with garlicky black beans; serve soft, beans split if firm.", "allergens": ["dairy"], "ingredients": ["white rice", "canned black beans (no-salt-added, rinsed)", "garlic", "unsalted butter", "neutral oil", "salt"], "cold": true, "yield": "3-4 servings", "freezer": "Freeze rice and beans up to 1 month; reheat with a splash of water.", "nutrients": ["protein", "iron", "fiber"], "flag": "Use oil instead of butter to keep dairy-free; gently mash any firm beans.", "steps": ["Saute 1 minced garlic clove in butter or oil over low heat ~1 min until fragrant.", "Add 1 cup rinsed white rice, stir, add 2 cups water and a tiny pinch of salt; simmer covered ~18 min.", "Separately warm 1.5 cups rinsed black beans with a little water and garlic ~10 min.", "Cool, serve soft rice topped with beans; lightly mash any firm beans."]},
  {"id": "l-mild-jollof-rice", "name": "Mild Jollof-Style Rice with Carrots", "category": "grain", "recipe": true, "prep": "Tomato-simmered rice with grated carrot, NO heat/pepper; grate carrot and cook rice fully soft.", "allergens": [], "ingredients": ["white rice", "tomato paste", "low-sodium vegetable broth", "carrot", "onion", "neutral oil", "salt"], "cold": true, "yield": "4 servings", "freezer": "Freeze up to 1 month; reheat with a splash of broth.", "nutrients": ["vitc", "fiber", "iron"], "flag": "No chili/scotch-bonnet so zero heat; carrot grated so no firm chunks.", "steps": ["Saute 1/2 finely diced onion and 1 grated carrot in oil over low heat ~5 min.", "Stir in 2 tbsp tomato paste, cook 1-2 min, add 1 cup rice and 2 cups low-sodium broth.", "Simmer covered ~18-20 min until rice is fully soft.", "Cool, fluff, pack; serve cold with an ice pack or warm in a thermos."]},
  {"id": "l-moin-moin", "name": "Moin-Moin (Steamed Bean Pudding)", "category": "protein", "recipe": true, "prep": "Steam smooth blended black-eyed-pea pudding; smooth soft texture, cut into ~1/2\" pieces.", "allergens": ["egg"], "ingredients": ["peeled black-eyed peas", "egg", "onion", "neutral oil", "low-sodium broth", "salt"], "cold": true, "yield": "4-6 portions", "freezer": "Freeze steamed pudding up to 1 month; thaw and steam to refresh.", "nutrients": ["protein", "iron", "fiber"], "flag": "Blend fully smooth so no firm bean bits; cut into ~1/2\" cubes.", "steps": ["Soak black-eyed peas ~1 hr, rub and rinse off skins for a smooth result.", "Blend peas with 1/4 onion, 2 tbsp oil, 1 egg, and enough low-sodium broth for a smooth pourable batter; tiny pinch salt.", "Pour into small greased heatproof cups and steam covered over simmering water ~35-40 min until set.", "Cool, unmold, cut into ~1/2\" pieces before packing."]},
  {"id": "l-mild-misir-wot", "name": "Mild Red Lentil Stew (Misir Wot, No Heat)", "category": "protein", "recipe": true, "prep": "Simmer red lentils soft with carrot and tomato, NO berbere/chili; cook to a soft stew.", "allergens": ["dairy"], "ingredients": ["red lentils", "carrot", "tomato paste", "fresh ginger", "garlic", "unsalted butter", "onion", "salt"], "cold": false, "yield": "4 servings", "freezer": "Freeze up to 2 months; reheat gently, thin with water.", "nutrients": ["protein", "iron", "fiber"], "flag": "NO berbere or chili so zero heat; use oil instead of butter to keep dairy-free. Pack warm in a thermos.", "steps": ["Saute 1/2 diced onion, 1 grated carrot, 1 minced garlic, and a little grated ginger in butter over low heat ~5 min.", "Stir in 2 tbsp tomato paste, cook 1-2 min (no berbere/chili).", "Add 1 cup rinsed red lentils and 3 cups water; simmer ~20-25 min until lentils collapse.", "Cool slightly, pack warm in a thermos or chill and serve cold."]},
  {"id": "m-tahini-free-falafel-patties", "name": "Tahini-Free Baked Falafel Patties", "category": "protein", "recipe": true, "prep": "Bake soft chickpea-herb patties; serve flattened ~1/2\" thick, broken into bite pieces.", "allergens": ["wheat"], "ingredients": ["canned chickpeas", "fresh parsley", "onion", "garlic", "ground cumin", "all-purpose flour", "olive oil", "baking soda"], "cold": true, "yield": "8 small patties", "freezer": "Freeze baked patties up to 1 month; reheat from frozen at 350F.", "nutrients": ["protein", "iron", "fiber"], "flag": "Sesame-free / tahini-free falafel (no tahini, sesame oil, or sesame seeds). Nut-free.", "steps": ["Pulse 1.5 cups drained chickpeas, 1/3 cup parsley, 2 tbsp onion, 1 small garlic clove, 1 tsp cumin, 1/4 tsp baking soda until coarse and moist.", "Mix in 2-3 tbsp flour until the mash just holds; do not over-process.", "Form 8 small patties, flatten each to ~1/2\" thick.", "Brush both sides lightly with olive oil, place on a lined tray.", "Bake at 375F for 18-22 min, flipping halfway, until set and pale golden.", "Cool fully, then break each patty into 1/2\" pieces before packing with an ice pack."]},
  {"id": "m-mujadara-lentils-rice", "name": "Mujadara (Red Lentils, Rice & Caramelized Onion)", "category": "grain", "recipe": true, "prep": "Simmer soft red lentils with rice and sweet caramelized onion; pack warm in a thermos, mince onion fine.", "allergens": [], "ingredients": ["red lentils", "white rice", "onion", "olive oil", "ground cumin"], "cold": false, "yield": "About 3 toddler portions", "freezer": "Freeze cooled in portions up to 2 months; thaw and reheat with a splash of water.", "nutrients": ["protein", "iron", "fiber"], "flag": "Sesame-free and nut-free. Naturally soft, low-sodium comfort grain.", "steps": ["Cook 2 thinly sliced onions in 2 tbsp olive oil over medium-low 12-15 min until deep golden, then finely mince half.", "Rinse 1/2 cup red lentils and 1/2 cup rice; add to a pot with 2.5 cups water and 1 tsp cumin.", "Simmer covered 18-20 min until lentils and rice are very tender.", "Stir in the minced caramelized onion; mash slightly if firm.", "Spoon hot into a warmed thermos."]},
  {"id": "m-white-bean-herb-dip-pita", "name": "White Bean & Herb Dip with Soft Pita Strips", "category": "protein", "recipe": true, "prep": "Blend creamy cannellini dip (no tahini); serve thinly spread with thin soft pita strips.", "allergens": ["wheat"], "ingredients": ["canned cannellini beans", "lemon", "fresh parsley", "olive oil", "garlic", "soft pita bread"], "cold": true, "yield": "About 1 cup dip + 1 pita", "freezer": "Dip freezes up to 1 month; pita best fresh.", "nutrients": ["protein", "fiber", "iron"], "flag": "Tahini-free / sesame-free white bean dip (classic versions use tahini; this omits all sesame). Nut-free.", "steps": ["Blend 1 cup drained cannellini beans, 1 tbsp lemon juice, 1 tbsp parsley, 2 tbsp olive oil, and a tiny bit of garlic until smooth.", "Loosen with 1-2 tbsp water if thick so it spreads thin.", "Cut soft pita into thin strips about 1/2\" wide and 2\" long.", "Pack dip and pita separately; keep cold with an ice pack.", "Serve dip spread thinly on the strips, not as a thick scoop."]},
  {"id": "m-yogurt-tzatziki-veg-sticks", "name": "Greek-Yogurt Tzatziki with Soft-Steamed Veg Sticks", "category": "dairy", "recipe": true, "prep": "Whisk grated-squeezed cucumber into yogurt; serve with soft-steamed veg sticks, grate raw cucumber.", "allergens": ["dairy"], "ingredients": ["plain greek yogurt", "cucumber", "fresh dill", "lemon", "carrots"], "cold": true, "yield": "About 3/4 cup dip + veg", "freezer": "Best fresh (yogurt separates if frozen).", "nutrients": ["calcium", "protein", "vitc"], "flag": "Sesame-free and nut-free. Cucumber is grated, not in rounds, for under-4 safety.", "steps": ["Grate 1/2 cucumber, squeeze out the liquid in a clean towel.", "Stir grated cucumber into 3/4 cup greek yogurt with 1 tsp chopped dill and a small squeeze of lemon.", "Steam carrot sticks and cucumber sticks until soft enough to mash between fingers, ~5-7 min, then cool.", "Cut steamed veg into pieces about 1/2\" wide and no longer than a finger width.", "Pack dip and soft veg separately with an ice pack."]},
  {"id": "m-spinach-feta-phyllo-bites", "name": "Spinach & Feta Phyllo Bites", "category": "veg", "recipe": true, "prep": "Bake mini spinach-feta phyllo bundles; cool and quarter so each piece is a soft ~1/2\" bite.", "allergens": ["wheat", "dairy", "egg"], "ingredients": ["phyllo dough", "frozen spinach", "feta cheese", "egg", "butter"], "cold": true, "yield": "About 9 small bites", "freezer": "Freeze baked bites up to 1 month; reheat at 325F.", "nutrients": ["calcium", "iron", "protein"], "flag": "Sesame-free and nut-free (no sesame seeds on the phyllo). Quartered after baking for safe bite size.", "steps": ["Thaw and squeeze 1 cup frozen spinach very dry, then finely mince.", "Mix spinach with 1/3 cup crumbled feta and 1 beaten egg.", "Brush 4 phyllo sheets lightly with melted butter, stack, cut into small squares.", "Add a small spoon of filling to each square and fold into little bundles.", "Bake at 350F for 15-18 min until golden and set.", "Cool fully, then cut each bite into quarters (~1/2\" soft pieces)."]},
  {"id": "m-lemon-herb-rice-peas", "name": "Lemon-Herb Rice with Peas", "category": "grain", "recipe": true, "prep": "Fold soft peas and lemon-dill into tender rice; pack warm in a thermos, lightly mash peas.", "allergens": [], "ingredients": ["white rice", "frozen peas", "lemon", "fresh dill", "olive oil"], "cold": false, "yield": "About 2 toddler portions", "freezer": "Freeze plain rice base up to 1 month; add fresh lemon and dill after reheating.", "nutrients": ["fiber", "protein", "vitc"], "flag": "Sesame-free and nut-free. Peas lightly mashed so they aren't round choke-size.", "steps": ["Cook 1/2 cup rice in 1 cup water until very tender, ~15 min.", "Stir in 1/3 cup peas and warm through until soft, ~3 min.", "Lightly mash some peas with a fork so they aren't whole spheres.", "Fold in 1 tsp olive oil, a small squeeze of lemon, and 1 tsp chopped dill.", "Spoon hot into a warmed thermos."]},
  {"id": "m-chicken-kofta-baked", "name": "Baked Chicken Kofta (Mild Cinnamon & Allspice)", "category": "protein", "recipe": true, "prep": "Bake mild spiced chicken kofta fingers; break into ~1/2\" pieces and pack warm in a thermos.", "allergens": ["egg"], "ingredients": ["ground chicken", "fresh parsley", "onion", "egg", "ground cinnamon", "ground allspice", "olive oil"], "cold": false, "yield": "About 8 small kofta", "freezer": "Freeze baked kofta up to 2 months; reheat from frozen at 350F.", "nutrients": ["protein", "iron"], "flag": "Sesame-free and nut-free. Mild warm spice, no chili.", "steps": ["Mix 1/2 lb ground chicken with 2 tbsp grated onion, 1 tbsp minced parsley, 1 small beaten egg, 1/4 tsp cinnamon, a pinch of allspice.", "Shape into 8 small soft logs about finger-length.", "Brush lightly with olive oil, place on a lined tray.", "Bake at 375F for 18-20 min until cooked through to 165F.", "Cool slightly, then break each into ~1/2\" pieces before packing warm in a thermos."]},
  {"id": "m-menemen-soft-egg-scramble", "name": "Menemen (Soft Egg Scramble with Pepper & Tomato)", "category": "protein", "recipe": true, "prep": "Slow-scramble eggs with soft-cooked pepper, tomato and onion; serve in small soft curds.", "allergens": ["egg", "dairy"], "ingredients": ["eggs", "bell pepper", "tomato", "onion", "butter"], "cold": true, "yield": "About 2 toddler portions", "freezer": "Best fresh (eggs turn rubbery when frozen).", "nutrients": ["protein", "vitc", "iron"], "flag": "Sesame-free and nut-free. Veg cooked very soft and finely chopped.", "steps": ["Finely chop 2 tbsp onion, 1/4 bell pepper, and 1/2 tomato (skin removed).", "Cook the veg in 1 tsp butter over medium-low 6-8 min until very soft.", "Add 2 beaten eggs and stir gently over low heat until set in small soft curds, ~3-4 min.", "Cool to just warm, breaking up any large pieces.", "Pack with an ice pack."]},
  {"id": "e-mini-frittata-squares", "name": "Mini Frittata Squares with Ricotta & Spinach", "category": "protein", "recipe": true, "prep": "Bake egg-ricotta-spinach, cool, cut into ~1/2\" squares so they're easy to chew.", "allergens": ["egg", "dairy"], "ingredients": ["eggs", "whole-milk ricotta", "baby spinach", "parmesan cheese", "butter or olive oil", "salt"], "cold": true, "yield": "9 small squares", "freezer": "Freeze cooked squares up to 1 month; thaw overnight in fridge.", "nutrients": ["protein", "calcium", "iron"], "flag": "Contains egg and dairy.", "steps": ["Finely chop 1 cup baby spinach and wilt in a buttered pan over medium heat 2 min, then cool.", "Whisk 4 eggs with 1/3 cup ricotta and 2 tbsp grated parmesan; stir in the cooled spinach.", "Pour into a buttered 8x8 pan and bake at 350F for 18-20 min until set.", "Cool fully, then cut into ~1/2\" squares before packing."]},
  {"id": "e-baked-pastina-butter-parm", "name": "Baked Pastina with Butter & Parmesan", "category": "grain", "recipe": true, "prep": "Cook tiny pastina very soft, toss with butter and parmesan; serve loose, not in a sticky clump.", "allergens": ["wheat", "dairy"], "ingredients": ["pastina (tiny star pasta)", "butter", "parmesan cheese", "low-sodium broth or water"], "cold": true, "yield": "About 1.5 cups", "freezer": "Freeze portions up to 1 month; reheat with a splash of water.", "nutrients": ["protein", "calcium"], "flag": "Contains wheat and dairy.", "steps": ["Cook 1/2 cup pastina in low-sodium broth or water over medium heat 7-9 min until very soft.", "Drain lightly, leaving a little liquid so it stays loose.", "Stir in 1 tbsp butter and 2 tbsp grated parmesan until creamy.", "Cool and pack loose; break up any clumps."]},
  {"id": "e-polenta-tomato-ricotta", "name": "Polenta Squares with Tomato & Ricotta", "category": "grain", "recipe": true, "prep": "Set polenta firm, cut into ~1/2\" squares, top with mild tomato and ricotta.", "allergens": ["dairy"], "ingredients": ["polenta or fine cornmeal", "low-sodium tomato sauce", "whole-milk ricotta", "parmesan cheese", "butter", "low-sodium broth or water"], "cold": true, "yield": "About 12 squares", "freezer": "Freeze plain cooked squares up to 1 month; add toppings fresh.", "nutrients": ["calcium", "fiber", "vitc"], "flag": "Contains dairy. Naturally wheat-free.", "steps": ["Whisk 1/2 cup cornmeal into 2 cups simmering low-sodium broth and cook 15-20 min until very thick.", "Stir in 1 tbsp butter and 1 tbsp parmesan, spread 1/2\" thick on a pan, chill until firm.", "Cut into ~1/2\" squares.", "Warm 2 tbsp low-sodium tomato sauce, spoon a little on each square with a dab of ricotta; serve room temp or cold."]},
  {"id": "e-gnocchi-mild-tomato", "name": "Gnocchi with Mild Tomato Sauce", "category": "grain", "recipe": true, "prep": "Boil gnocchi soft, then QUARTER each one and toss in mild tomato-butter sauce.", "allergens": ["wheat", "dairy"], "ingredients": ["potato gnocchi", "low-sodium tomato sauce", "butter", "parmesan cheese"], "cold": true, "yield": "About 1.5 cups", "freezer": "Best fresh; sauce alone freezes up to 1 month.", "nutrients": ["protein", "fiber", "vitc"], "flag": "Contains wheat and dairy. QUARTER every gnocchi - round pieces are a choking risk whole. Thermos-friendly warm or pack cold.", "steps": ["Boil gnocchi per package until they float plus 1 min, so they're very soft, then drain.", "Quarter each gnocchi (cut in half, then halve again) so no piece is round or larger than 1/2\".", "Warm 1/3 cup low-sodium tomato sauce with 1 tsp butter and toss the gnocchi pieces.", "Stir in 1 tbsp parmesan; cool to pack cold or load warm into a preheated thermos."]},
  {"id": "e-minestrone-toddler", "name": "Toddler Minestrone with Tiny Pasta & Beans", "category": "grain", "recipe": true, "prep": "Simmer soft-diced veg, beans and tiny pasta in low-sodium broth; dice veg <=1/2\" and cook fork-soft.", "allergens": ["wheat"], "ingredients": ["stelline or ditalini pasta", "carrot", "zucchini", "canned white beans (no-salt-added)", "low-sodium tomato sauce or crushed tomatoes", "low-sodium vegetable broth", "olive oil"], "cold": false, "yield": "About 4 cups", "freezer": "Freeze up to 2 months; pasta softens further on reheat.", "nutrients": ["fiber", "iron", "protein"], "flag": "Contains wheat. Pack warm in a preheated thermos.", "steps": ["Dice 1 carrot and 1 small zucchini into <=1/2\" pieces; saute in 1 tsp olive oil 3 min.", "Add 3 cups low-sodium broth and 1/3 cup tomato sauce; simmer 12 min until carrot is fork-soft.", "Rinse 1/2 cup white beans well, lightly mash, add with 1/3 cup tiny pasta; simmer 7-8 min until pasta is very soft.", "Check every veg piece is soft and <=1/2\"; cool slightly and load into a preheated thermos."]},
  {"id": "e-potato-pancakes-soft", "name": "Soft Potato Pancakes", "category": "grain", "recipe": true, "prep": "Pan-cook grated-potato pancakes until soft inside, cut into ~1/2\" strips.", "allergens": ["egg", "wheat", "dairy"], "ingredients": ["russet potatoes", "egg", "all-purpose flour", "butter", "salt"], "cold": true, "yield": "About 6 small pancakes", "freezer": "Freeze cooked pancakes up to 1 month; reheat in a pan.", "nutrients": ["protein", "fiber", "vitc"], "flag": "Contains egg and wheat.", "steps": ["Grate 2 peeled potatoes, squeeze out the liquid, mix with 1 egg, 2 tbsp flour, a pinch of salt.", "Melt butter in a pan over medium-low heat; drop small 2\" portions and flatten thin.", "Cook 3-4 min per side until golden and the centers are cooked through and soft.", "Cool, then cut each pancake into ~1/2\" strips before packing."]},
  {"id": "e-cheese-pierogi", "name": "Soft Cheese & Potato Pierogi", "category": "grain", "recipe": true, "prep": "Boil potato-cheddar pockets until soft, toss in butter, cut into ~1/2\" pieces.", "allergens": ["wheat", "egg", "dairy"], "ingredients": ["all-purpose flour", "egg", "russet potatoes", "mild cheddar cheese", "butter", "milk", "salt"], "cold": true, "yield": "About 12 pierogi", "freezer": "Freeze boiled-and-cooled pierogi up to 2 months; reheat in butter.", "nutrients": ["protein", "calcium", "fiber"], "flag": "Contains wheat, egg, and dairy. Cut each pierogi into small <=1/2\" pieces - whole pockets are too big.", "steps": ["Make dough from 1.5 cups flour, 1 egg, ~1/2 cup water; rest 20 min, roll thin, cut 3\" rounds.", "Mash 2 boiled potatoes with 1/2 cup shredded mild cheddar and a splash of milk.", "Spoon filling onto rounds, fold and seal edges, boil 4-5 min until they float and dough is soft.", "Toss in butter; cool and cut each pierogi into ~1/2\" pieces before packing."]},
  {"id": "e-crustless-leek-cheese-quiche", "name": "Crustless Leek & Cheese Quiche", "category": "protein", "recipe": true, "prep": "Bake custardy egg-milk-leek-cheddar mix, cool, cut into ~1/2\" pieces.", "allergens": ["egg", "dairy"], "ingredients": ["eggs", "whole milk", "heavy cream", "leek", "mild cheddar cheese", "butter", "salt"], "cold": true, "yield": "9 small pieces", "freezer": "Freeze cooked pieces up to 1 month; thaw in fridge.", "nutrients": ["protein", "calcium", "iron"], "flag": "Contains egg and dairy. Naturally wheat-free (crustless).", "steps": ["Slice the white part of 1 leek thin, rinse well, cook in butter over medium-low 6-8 min until very soft; cool.", "Whisk 4 eggs with 1/2 cup whole milk and 2 tbsp cream; stir in the leek and 1/2 cup shredded mild cheddar.", "Pour into a buttered 8x8 pan and bake at 350F for 22-25 min until set.", "Cool fully, then cut into ~1/2\" pieces before packing."]},
  {"id": "b-cheese-herb-muffins", "name": "Savory Cheese & Herb Muffins", "category": "dairy", "recipe": true, "prep": "Bake in mini muffin tin; cool fully and serve at room temp or cold with ice pack.", "allergens": ["dairy", "egg", "wheat"], "ingredients": ["all-purpose flour", "baking powder", "shredded mild cheddar cheese", "eggs", "whole milk", "unsalted butter", "dried mixed herbs (parsley, chives)"], "cold": true, "yield": "12 mini muffins", "freezer": "Freeze cooled muffins up to 1 month; thaw overnight in fridge.", "nutrients": ["protein", "calcium", "fat"], "flag": "Contains dairy, egg, wheat.", "steps": ["Heat oven to 375F and grease a 12-cup mini muffin tin.", "Whisk 1 cup flour, 1.5 tsp baking powder, 1 tsp dried herbs.", "Beat 1 egg with 1/2 cup milk and 2 tbsp melted butter, fold in 3/4 cup shredded cheddar.", "Combine wet and dry until just mixed; spoon into cups.", "Bake 15-18 min until set; cool fully before packing."]},
  {"id": "b-mac-cheese-cups", "name": "Baked Mac & Cheese Cups", "category": "grain", "recipe": true, "prep": "Bake mini mac & cheese in muffin tin; cook pasta soft (not al dente) and cool fully.", "allergens": ["wheat", "dairy"], "ingredients": ["mini macaroni pasta", "shredded mild cheddar cheese", "whole milk", "unsalted butter", "all-purpose flour", "plain breadcrumbs"], "cold": true, "yield": "12 mini cups", "freezer": "Freeze baked cups up to 1 month; reheat or thaw in fridge.", "nutrients": ["protein", "calcium", "fat"], "flag": "Contains wheat and dairy.", "steps": ["Heat oven to 375F and grease a mini muffin tin.", "Boil 1 cup mini macaroni until very soft (1-2 min past package time); drain.", "Melt 1 tbsp butter, whisk in 1 tbsp flour, then 3/4 cup milk; simmer 2 min until thick.", "Stir in 1 cup shredded cheddar until melted; fold in pasta.", "Spoon into cups, top with a pinch of breadcrumbs, bake 12-15 min until set; cool fully before packing."]},
  {"id": "b-butternut-cheese-muffins", "name": "Savory Butternut & Cheese Muffins", "category": "veg", "recipe": true, "prep": "Bake hidden-veg muffins; use smooth butternut puree (no lumps) and cool completely.", "allergens": ["wheat", "dairy", "egg"], "ingredients": ["all-purpose flour", "baking powder", "butternut squash puree", "shredded mild cheddar cheese", "eggs", "unsalted butter", "whole milk"], "cold": true, "yield": "12 mini muffins", "freezer": "Freeze cooled muffins up to 1 month; thaw overnight in fridge.", "nutrients": ["vitc", "calcium", "fiber"], "flag": "Contains wheat, dairy, egg.", "steps": ["Heat oven to 375F and grease a mini muffin tin.", "Whisk 1 cup flour with 1.5 tsp baking powder.", "Beat 1 egg with 1/2 cup butternut puree, 2 tbsp melted butter, 3 tbsp milk.", "Fold in 1/2 cup shredded cheddar, combine wet and dry until just mixed.", "Spoon into cups and bake 16-18 min until set; cool fully before packing."]},
  {"id": "b-salmon-cakes", "name": "Salmon Cakes", "category": "protein", "recipe": true, "prep": "Pan-cook small canned-salmon cakes; REMOVE ALL bones and skin, flake and inspect by hand.", "allergens": ["fish", "egg", "wheat", "dairy"], "ingredients": ["canned boneless skinless salmon", "plain breadcrumbs", "egg", "lemon", "unsalted butter or olive oil", "fresh parsley"], "cold": true, "yield": "8 small cakes", "freezer": "Freeze cooked cooled cakes up to 1 month; thaw in fridge.", "nutrients": ["protein", "iron", "calcium"], "flag": "Remove ALL salmon bones and skin; flake and inspect by hand. Omega-3 + iron.", "steps": ["Drain a 5 oz can of boneless skinless salmon; flake and pick through carefully to remove any bones or skin.", "Mix salmon with 1 beaten egg, 1/3 cup breadcrumbs, a squeeze of lemon, 1 tsp chopped parsley.", "Shape into 8 small flat cakes about 1/4\" thick.", "Pan-cook in a little butter or oil over medium heat 3-4 min per side until golden and cooked through.", "Cool fully, then cut each cake into halves or quarters before packing."]},
  {"id": "b-tuna-bean-patties", "name": "Tuna & White-Bean Patties", "category": "protein", "recipe": true, "prep": "Pan-cook tuna-and-bean patties; mash beans smooth and cook through; cut to small pieces.", "allergens": ["fish", "egg", "wheat"], "ingredients": ["canned tuna in water", "canned white beans (cannellini)", "egg", "plain breadcrumbs", "lemon", "olive oil"], "cold": true, "yield": "8 small patties", "freezer": "Freeze cooked cooled patties up to 1 month; thaw in fridge.", "nutrients": ["protein", "iron", "fiber"], "flag": "Use boneless canned tuna; inspect and break apart before mixing. Limit oily fish to ~1x/week.", "steps": ["Drain a 5 oz can of tuna and inspect; mash 1/2 cup white beans until smooth.", "Mix tuna, mashed beans, 1 beaten egg, 1/3 cup breadcrumbs, and a squeeze of lemon.", "Shape into 8 small flat patties about 1/4\" thick.", "Pan-cook in olive oil over medium heat 3-4 min per side until golden and cooked through.", "Cool fully, then cut into halves or quarters before packing."]},
  {"id": "b-corn-fritters", "name": "Soft Corn Fritters", "category": "veg", "recipe": true, "prep": "Pan-cook soft corn fritters; pulse or lightly mash corn so no whole round kernels remain.", "allergens": ["wheat", "egg", "dairy"], "ingredients": ["corn kernels (canned or thawed frozen)", "all-purpose flour", "egg", "whole milk", "baking powder", "olive oil"], "cold": true, "yield": "8 small fritters", "freezer": "Freeze cooked cooled fritters up to 1 month; thaw in fridge.", "nutrients": ["fiber", "protein", "vitc"], "flag": "Pulse/mash corn so no whole round kernels remain (choking).", "steps": ["Pulse or roughly mash 1 cup corn kernels so no whole kernels stay round.", "Whisk 1/2 cup flour, 1/2 tsp baking powder, 1 egg, 3 tbsp milk into a thick batter; stir in corn.", "Heat a little olive oil in a pan over medium heat.", "Drop small spoonfuls and flatten; cook 2-3 min per side until golden and cooked through.", "Cool fully, then cut into halves before packing."]},
  {"id": "b-zucchini-fritters", "name": "Zucchini Fritters", "category": "veg", "recipe": true, "prep": "Pan-cook grated-zucchini fritters; squeeze zucchini very dry and cook through.", "allergens": ["wheat", "egg", "dairy"], "ingredients": ["zucchini", "all-purpose flour", "egg", "shredded mild cheddar cheese", "baking powder", "olive oil"], "cold": true, "yield": "8 small fritters", "freezer": "Freeze cooked cooled fritters up to 1 month; thaw in fridge.", "nutrients": ["fiber", "calcium", "vitc"], "flag": "Contains wheat, egg, dairy.", "steps": ["Grate 1 medium zucchini, then squeeze in a clean towel until very dry.", "Mix zucchini with 1 beaten egg, 1/3 cup flour, 1/2 tsp baking powder, 1/3 cup shredded cheddar.", "Heat a little olive oil in a pan over medium heat.", "Drop small spoonfuls and flatten; cook 2-3 min per side until golden and cooked through.", "Cool fully, then cut into halves before packing."]},
  {"id": "b-white-fish-fingers", "name": "Homemade White-Fish Fingers", "category": "protein", "recipe": true, "prep": "Bake breaded cod strips; REMOVE ALL bones, check each strip; bake through and cut small.", "allergens": ["fish", "egg", "wheat"], "ingredients": ["cod fillet (boneless)", "plain breadcrumbs", "egg", "all-purpose flour", "olive oil", "lemon"], "cold": true, "yield": "10 soft strips", "freezer": "Freeze cooked cooled fingers up to 1 month; thaw in fridge.", "nutrients": ["protein", "iron"], "flag": "Remove ALL cod bones; press each strip to feel for bones before breading.", "steps": ["Heat oven to 400F and line a baking sheet with oiled parchment.", "Pat cod dry, run fingers along each piece to find and remove any bones, cut into strips about 1/2\" wide.", "Coat strips in flour, then beaten egg, then breadcrumbs.", "Place on the sheet, drizzle lightly with olive oil, bake 12-15 min until cooked through and flaky.", "Cool fully and cut strips into bite-size (~1/2\") pieces before packing."]},
  {"id": "s-butternut-chicken-soup", "name": "Butternut Squash & Chicken Soup", "category": "veg", "recipe": true, "prep": "Simmer squash, chicken & onion in broth, then puree fully smooth; blend until no lumps remain.", "allergens": ["dairy"], "ingredients": ["butternut squash", "boneless skinless chicken breast", "onion", "low-sodium chicken broth", "unsalted butter"], "cold": false, "yield": "4 toddler portions", "freezer": "Freeze up to 3 months in portions; thaw overnight and reheat to a boil before packing.", "nutrients": ["protein", "vitc", "fiber"], "flag": "Pack boiling-hot in a preheated thermos.", "steps": ["Peel and cube 3 cups butternut squash into 1/2\" pieces; dice 1/2 onion.", "Melt 1 tbsp butter in a pot; soften onion 3-4 min, add squash and 1 diced chicken breast.", "Pour in 3 cups broth, simmer covered 18-20 min until squash is fork-soft and chicken reaches 165F.", "Blend the whole pot fully smooth; check no lumps or fibrous strands remain.", "Reheat to a rolling boil, then pour into a preheated thermos."]},
  {"id": "s-lentil-sweet-potato-stew", "name": "Lentil & Sweet Potato Stew", "category": "protein", "recipe": true, "prep": "Simmer red lentils with sweet potato & carrot until very soft; cook until they mash easily, dice veg 1/2\".", "allergens": [], "ingredients": ["red lentils", "sweet potato", "carrot", "onion", "low-sodium vegetable broth"], "cold": false, "yield": "5 toddler portions", "freezer": "Freeze up to 3 months; thaw and reheat to a boil, add a splash of broth.", "nutrients": ["protein", "iron", "fiber"], "flag": "Pack boiling-hot in a preheated thermos; pair with a vitamin-C food to boost iron uptake.", "steps": ["Rinse 1 cup red lentils. Dice 1 small sweet potato, 1 carrot, and 1/2 onion into 1/2\" pieces.", "Soften onion in a pot 3 min, add sweet potato, carrot, lentils and 4 cups broth.", "Simmer covered 22-25 min until lentils break down and veg is very soft.", "Lightly mash with a fork for a thick soft texture; confirm all veg pieces squash easily.", "Reheat to a boil and pour into a preheated thermos."]},
  {"id": "s-chicken-rice-soup", "name": "Chicken & Rice Soup", "category": "grain", "recipe": true, "prep": "Mild ginger-turmeric chicken-rice soup; remove all ginger slices before packing, dice chicken 1/2\".", "allergens": [], "ingredients": ["boneless skinless chicken breast", "white rice", "low-sodium chicken broth", "carrot", "fresh ginger", "ground turmeric"], "cold": false, "yield": "4 toddler portions", "freezer": "Best fresh (rice softens further on freezing); refrigerate up to 2 days and reheat to a boil.", "nutrients": ["protein", "vitc"], "flag": "Pack boiling-hot in a preheated thermos.", "steps": ["Dice 1 chicken breast and 1 carrot into 1/2\" pieces; cut 2 thin ginger slices (kept whole for removal).", "Simmer 4 cups broth with carrot, ginger slices, and 1/4 tsp turmeric for 5 min.", "Add chicken and 1/3 cup rice; simmer 18-20 min until rice is very soft and chicken reaches 165F.", "Fish out and discard both ginger slices completely before serving.", "Reheat to a boil and pour into a preheated thermos."]},
  {"id": "s-leek-potato-soup", "name": "Leek & Potato Soup", "category": "veg", "recipe": true, "prep": "Simmer leek and potato in broth, blend smooth; wash leeks well and blend fully so there are no pieces.", "allergens": ["dairy"], "ingredients": ["leek", "potato", "low-sodium vegetable broth", "unsalted butter"], "cold": false, "yield": "4 toddler portions", "freezer": "Freeze up to 2 months; thaw and reheat to a boil, whisk to recombine.", "nutrients": ["vitc", "fiber"], "flag": "Pack boiling-hot in a preheated thermos.", "steps": ["Slice 1 leek (white/light-green only) and rinse thoroughly to remove grit; peel and dice 2 potatoes 1/2\".", "Melt 1 tbsp butter, soften leek 4-5 min without browning.", "Add potato and 3 cups broth; simmer covered 18-20 min until potato is fork-soft.", "Blend fully smooth; confirm no leek strands or potato lumps remain.", "Reheat to a boil and pour into a preheated thermos."]},
  {"id": "s-tomato-white-bean-soup", "name": "Creamy Tomato & White Bean Soup", "category": "protein", "recipe": true, "prep": "Simmer white beans, tomato & carrot, then blend creamy-smooth so soft beans have no whole skins.", "allergens": ["dairy"], "ingredients": ["canned white beans (no-salt-added)", "canned crushed tomatoes (no-salt-added)", "carrot", "onion", "low-sodium vegetable broth", "unsalted butter"], "cold": false, "yield": "5 toddler portions", "freezer": "Freeze up to 3 months; thaw and reheat to a boil, stir well.", "nutrients": ["protein", "iron", "fiber"], "flag": "Pack boiling-hot in a preheated thermos.", "steps": ["Drain and rinse 1 can white beans. Dice 1 carrot and 1/2 onion small.", "Melt 1 tbsp butter, soften onion and carrot 5 min.", "Add beans, 1 can crushed tomatoes, and 2 cups broth; simmer 15-18 min until carrot is very soft.", "Blend fully smooth and creamy; confirm no whole beans or bean skins remain.", "Reheat to a boil and pour into a preheated thermos."]},
  {"id": "s-beef-spinach-meatballs", "name": "Beef & Spinach Mini Meatballs", "category": "protein", "recipe": true, "prep": "Bake mini beef-spinach meatballs; quarter each round meatball lengthwise before packing.", "allergens": ["wheat", "egg"], "ingredients": ["lean ground beef", "frozen chopped spinach", "plain breadcrumbs", "egg"], "cold": true, "yield": "About 20 mini meatballs", "freezer": "Freeze cooked meatballs up to 3 months; thaw in fridge, then quarter before packing.", "nutrients": ["protein", "iron"], "flag": "Serve cold or room-temp; high-iron. Quarter each meatball - whole round balls are a choking risk.", "steps": ["Thaw and squeeze dry 1/2 cup chopped spinach; finely chop any larger pieces.", "Mix 1 lb ground beef, spinach, 1/3 cup breadcrumbs, and 1 beaten egg until just combined.", "Roll into 1\" mini meatballs and bake at 400F for 15-18 min until 160F internal and no pink.", "Cool fully; quarter each meatball lengthwise into small soft strips before packing.", "Pack cold with an ice pack."]},
  {"id": "s-mini-cottage-pie-cups", "name": "Mini Cottage Pie Cups", "category": "protein", "recipe": true, "prep": "Beef-and-veg base under a soft mashed-potato top; dice veg 1/2\" and lightly mash peas.", "allergens": ["dairy"], "ingredients": ["lean ground beef", "carrot", "potato", "frozen peas", "low-sodium beef broth", "unsalted butter"], "cold": false, "yield": "4 toddler portions", "freezer": "Freeze assembled cups up to 2 months; reheat to steaming hot throughout before packing.", "nutrients": ["protein", "iron", "fiber"], "flag": "Pack boiling-hot in a preheated thermos; high-iron.", "steps": ["Boil 2 peeled diced potatoes until fork-soft, mash with 1 tbsp butter until smooth.", "Brown 1/2 lb ground beef; add 1 finely diced carrot and 1/3 cup peas with 1/2 cup broth, simmer 10 min until carrot is very soft.", "Lightly mash the peas and confirm all veg is 1/2\" and soft.", "Layer beef-veg mix into cups and top with mashed potato; warm through until steaming.", "Pack the hot mixture into a preheated thermos."]},
  {"id": "s-hidden-veggie-pasta-sauce", "name": "Hidden-Veggie Tomato Pasta Sauce", "category": "veg", "recipe": true, "prep": "Blended tomato sauce with hidden zucchini, carrot & spinach; blend fully smooth, serve over soft small pasta.", "allergens": [], "ingredients": ["canned crushed tomatoes (no-salt-added)", "zucchini", "carrot", "fresh spinach", "onion"], "cold": false, "yield": "About 3 cups sauce", "freezer": "Freeze up to 3 months in portions; thaw and reheat to a boil.", "nutrients": ["vitc", "fiber", "iron"], "flag": "Serve over soft-cooked small pasta; pack thermos-hot or cold over pre-cooked pasta.", "steps": ["Dice 1/2 onion, 1 carrot, and 1 small zucchini; add a handful of spinach.", "Soften onion and carrot 5 min, add zucchini and spinach, cook 5 min until wilted and soft.", "Add 1 can crushed tomatoes, simmer 12-15 min until carrot is very soft.", "Blend fully smooth; confirm no veg pieces remain so it's safe over pasta.", "Toss with soft-cooked small pasta (cut to 1/2\" if needed); pack hot in a thermos or cold with an ice pack."]},
  {"id": "n-blueberry-oat-mini-muffins", "name": "Blueberry-Oat Mini Muffins", "category": "snack", "recipe": true, "prep": "Bake mini muffins with quartered berries; quarter every blueberry before folding in.", "allergens": ["wheat", "egg", "dairy"], "ingredients": ["rolled oats", "all-purpose flour", "fresh blueberries", "egg", "milk", "baking powder", "ripe banana or 1 tbsp maple syrup", "neutral oil"], "cold": false, "yield": "12 mini muffins", "freezer": "Freeze cooled muffins up to 1 month; thaw at room temp or pack frozen as an ice pack.", "nutrients": ["fiber", "calcium", "protein"], "flag": "Mini muffin size only; a full-size muffin is a choking-shape risk for under-4.", "steps": ["Heat oven to 350F and grease a 12-cup mini muffin tin.", "QUARTER all blueberries with a knife so no whole round berry remains.", "Whisk 1 egg, 1/2 cup milk, 1 mashed ripe banana (or 1 tbsp maple syrup) and 2 tbsp oil; stir in 3/4 cup flour, 1/2 cup oats, 1 tsp baking powder until just combined.", "Fold in quartered berries, divide into cups, bake 14-16 min until set.", "Cool fully; cut any larger muffin in half before serving."]},
  {"id": "n-sweet-potato-cinnamon-rounds", "name": "Sweet-Potato Cinnamon Baked Rounds", "category": "snack", "recipe": true, "prep": "Bake soft cinnamon-sweet-potato rounds; keep thin and soft-bake so they stay pliable, never hard.", "allergens": ["wheat", "egg"], "ingredients": ["sweet potato puree", "all-purpose flour", "egg", "ground cinnamon", "baking powder", "neutral oil"], "cold": false, "yield": "About 16 small rounds", "freezer": "Freeze cooled rounds up to 1 month in a single layer; thaw before packing.", "nutrients": ["vitc", "fiber"], "flag": "Naturally sweetened by the sweet potato; no added sugar needed.", "steps": ["Heat oven to 375F and line a sheet with parchment.", "Mix 3/4 cup sweet potato puree, 1 egg, 1 tbsp oil, then stir in 3/4 cup flour, 1/2 tsp cinnamon and 1 tsp baking powder into a soft batter.", "Drop small spoonfuls and gently flatten into thin rounds about 1/4\" thick.", "Bake 12-15 min until just set and springy; do NOT bake to crisp, they must stay soft.", "Cool, then break or cut any round larger than 1/2\" before serving."]},
  {"id": "n-banana-mini-muffins", "name": "Banana Mini Muffins", "category": "snack", "recipe": true, "prep": "Bake banana-sweetened mini muffins; serve mini size, halve any larger muffin.", "allergens": ["wheat", "egg"], "ingredients": ["ripe banana", "all-purpose flour", "egg", "rolled oats", "baking powder", "ground cinnamon", "neutral oil"], "cold": false, "yield": "12 mini muffins", "freezer": "Freeze cooled muffins up to 1 month; thaw at room temp before packing.", "nutrients": ["fiber", "protein"], "flag": "Sweetened only by ripe banana; no added sugar.", "steps": ["Heat oven to 350F and grease a mini muffin tin.", "Mash 2 very ripe bananas, whisk in 1 egg and 2 tbsp oil.", "Stir in 3/4 cup flour, 1/3 cup oats, 1 tsp baking powder and 1/4 tsp cinnamon until just combined.", "Divide into cups and bake 13-15 min until set.", "Cool fully; cut any muffin over 1/2\" in half before serving."]},
  {"id": "n-soft-baked-apple-cinnamon-chips", "name": "Soft-Baked Apple Cinnamon Chips", "category": "fruit", "recipe": true, "prep": "Low-temp bake thin apple slices until pliable; pull while still soft and bendy, never crisp.", "allergens": [], "ingredients": ["apple", "ground cinnamon"], "cold": false, "yield": "About 1 cup soft chips", "freezer": "Best fresh; store in an airtight container 2-3 days.", "nutrients": ["fiber", "vitc"], "flag": "Pliable, not crisp; a crisp/hard apple chip is a choking hazard for under-4.", "steps": ["Heat oven to 225F and line a sheet with parchment.", "Core and slice 1 apple into very thin rounds about 1/8\", then dust lightly with cinnamon.", "Bake 60-90 min, flipping once, until dried but still soft and bendable, NOT crisp.", "Cool; they should fold without snapping.", "Tear or cut any piece larger than 1/2\" before serving."]},
  {"id": "n-frozen-yogurt-fruit-bark", "name": "Frozen Yogurt & Fruit Bark", "category": "snack", "recipe": true, "prep": "Freeze yogurt-banana spread with soft fruit, then break into small pieces; quarter any berries on top.", "allergens": ["dairy"], "ingredients": ["plain whole-milk yogurt", "ripe banana", "soft berries (raspberries or blueberries)"], "cold": true, "yield": "About 16 bite pieces", "freezer": "Keep frozen until packing; serve with an ice pack and eat same day.", "nutrients": ["calcium", "protein"], "flag": "Perishable and must stay frozen; pack with an ice pack.", "steps": ["Line a small sheet with parchment.", "Mash 1 ripe banana and stir into 1 cup plain yogurt; spread 1/4\" thick on the sheet.", "QUARTER blueberries or break raspberries into small bits and scatter on top.", "Freeze 3-4 hours until solid.", "Break into pieces about 1/2\"; keep frozen and pack with an ice pack."]},
  {"id": "n-cottage-cheese-soft-fruit-cup", "name": "Cottage Cheese + Soft Fruit Cup", "category": "dairy", "recipe": true, "prep": "Spoon cottage cheese with diced soft fruit; dice peach and quarter berries to under 1/2\".", "allergens": ["dairy"], "ingredients": ["small-curd cottage cheese", "ripe soft peach", "soft berries (blueberries or raspberries)"], "cold": true, "yield": "1 small cup", "freezer": "Best fresh; keep refrigerated and pack with an ice pack.", "nutrients": ["calcium", "protein"], "flag": "Perishable; pack cold with an ice pack. Choose low-sodium cottage cheese.", "steps": ["Spoon 1/3 cup small-curd cottage cheese into a lidded cup.", "Peel and dice 1/4 ripe peach into pieces under 1/2\".", "QUARTER any blueberries or break raspberries into small bits.", "Stir the fruit gently into the cottage cheese.", "Seal and pack cold with an ice pack."]},
  {"id": "n-guacamole-soft-tortilla-dippers", "name": "Guacamole + Soft Corn-Tortilla Dippers", "category": "snack", "recipe": true, "prep": "Mash avocado with a little lime; serve with warm soft tortilla strips, never crisp chips.", "allergens": [], "ingredients": ["ripe avocado", "lime", "soft corn tortilla", "salt"], "cold": true, "yield": "1 serving with dippers", "freezer": "Best fresh; guacamole browns, pack same day with an ice pack.", "nutrients": ["fat", "fiber"], "flag": "Perishable; soft (warmed) tortilla only, never crisp tortilla chips for under-4.", "steps": ["Mash 1/2 ripe avocado smooth with a squeeze of lime and a tiny pinch of salt.", "Warm 1 corn tortilla until soft and pliable.", "Cut the warm tortilla into thin strips under 1/2\" wide.", "Pack guacamole in a sealed cup pressed flat to limit browning.", "Keep cold with an ice pack; serve the strips soft, not crisped."]},
  {"id": "n-tahini-free-hummus-pita-strips", "name": "Tahini-Free Hummus + Soft Pita Strips", "category": "snack", "recipe": true, "prep": "Blend chickpeas with olive oil, lemon and garlic (NO tahini); serve with soft pita strips.", "allergens": ["wheat"], "ingredients": ["canned chickpeas", "olive oil", "lemon", "garlic", "soft pita bread", "salt"], "cold": true, "yield": "About 1 cup hummus plus strips", "freezer": "Freeze hummus up to 1 month; thaw and stir. Pita best fresh.", "nutrients": ["protein", "iron", "fiber"], "flag": "Tahini- and sesame-free by design (sesame is banned); keep garlic and salt minimal.", "steps": ["Drain and rinse 1 cup chickpeas.", "Blend chickpeas with 2 tbsp olive oil, 1 tbsp lemon juice, a tiny piece of garlic and 2-3 tbsp water until very smooth (NO tahini).", "Warm 1 soft pita and cut into thin strips under 1/2\" wide.", "Pack hummus in a sealed cup; offer it as a thin dip.", "Keep cold with an ice pack."]},
];
